woowacourse-teams/2025-mul-kkam

.github/ISSUE_TEMPLATE/default_issue_template.md

- close #7
- Issue 템플릿이 적용되지 않는 오류 해결
1. `''` 가 추가되었습니당,,

[AN/BE][fix]: Issue 템플릿이 적용되지 않는 오류 해결

---

android/app/build.gradle.kts
android/build.gradle.kts
android/gradle/libs.versions.toml
android/settings.gradle.kts

- close #21
- 기획에 필요한 라이브러리 추가
1. 직렬화 플러그인 적용
2. 이미지 라이브러리 적용
3. 차트 라이브러리 적용

[AN][chore]: 기획에 필요한 플러그인 및 라이브러리 추가

---

.github/workflows/backend-ci.yml

- close #
- CI 워크플로우 적용
1. 
2. 
3.

[BE][chore]: 백엔드 CI 워크플로우 추가

---

android/app/src/main/java/com/mulkkam/domain/DailyWaterIntake.kt
android/app/src/main/java/com/mulkkam/domain/WaterRecord.kt
android/app/src/main/java/com/mulkkam/ui/record/RecordFragment.kt
android/app/src/main/java/com/mulkkam/ui/record/adapter/RecordAdapter.kt
android/app/src/main/java/com/mulkkam/ui/record/adapter/WaterRecordViewHolder.kt
android/app/src/main/res/layout/fragment_record.xml
android/app/src/main/res/layout/item_water_record.xml
android/app/src/main/res/values/strings.xml

- close #33 
- 기록 화면의 UI 구현
1. RecordFragment 추가
2. 화면에 필요한 domain model 추가 ( DailyWaterIntake, WaterRecord )
3. 차트 그리기 로직 추가

[AN][feat]: 기록 화면 UI 구현

---

.github/workflows/backend-cd.yml
backend/src/main/java/backend/mulkkam/MulKkamApplication.java

chore: CD 스프링 네트워크 설정

---

.github/workflows/backend-cd.yml
backend/src/main/java/backend/mulkkam/MulKkamApplication.java

chore: CD 환경변수 경로 변경

---

.github/workflows/backend-cd.yml
backend/src/main/java/backend/mulkkam/MulKkamApplication.java

chore: CD 경로 변경

---

.github/workflows/backend-cd.yml
backend/src/main/java/backend/mulkkam/MulKkamApplication.java

chore: CD 명령어 변경

---

backend/src/main/java/backend/mulkkam/intake/controller/IntakeAmountController.java
backend/src/main/java/backend/mulkkam/intake/controller/IntakeHistoryController.java
backend/src/main/java/backend/mulkkam/intake/dto/IntakeHistoryResponse.java
backend/src/main/java/backend/mulkkam/intake/service/IntakeHistoryService.java

- 기존 API 명세와 다른 응답 형태 수정
- 잘못 매핑된 HTTP method 수정

[BE][fix]: 잘못된 dto 형태 수정

---

backend/src/main/java/backend/mulkkam/common/config/WebConfiguration.java

- close #78 
- API 명세서 CORS 해결
1. `addCORSMappings` 추가

[BE][feat]: API 명세서 CORS 해결

---

backend/src/main/java/backend/mulkkam/cup/dto/response/CupResponse.java
backend/src/test/java/backend/mulkkam/cup/service/CupServiceIntegrationTest.java
backend/src/test/java/backend/mulkkam/cup/service/CupServiceUnitTest.java

- close #96 
- 응답을 수정합니다.
1. 
2. 
3.

[BE][fix]: 응답 수정

---

android/app/src/main/java/com/mulkkam/data/remote/model/request/AddCupRequest.kt
android/app/src/main/java/com/mulkkam/data/remote/service/CupsService.kt
android/app/src/main/java/com/mulkkam/data/repository/CupsRepository.kt
android/app/src/main/java/com/mulkkam/di/NetworkInjection.kt
android/app/src/main/java/com/mulkkam/di/RepositoryInjection.kt
android/app/src/main/java/com/mulkkam/ui/settingwater/SettingWaterActivity.kt
android/app/src/main/java/com/mulkkam/ui/settingwater/dialog/SettingWaterCupFragment.kt
android/app/src/main/java/com/mulkkam/ui/settingwater/dialog/SettingWaterCupViewModel.kt
android/app/src/main/java/com/mulkkam/ui/settingwater/model/CupUiModel.kt
android/app/src/main/res/layout/fragment_setting_water_cup.xml

- close #87
- 컵 추가 API 연결했습니다. 수정은 없어서 일단 추가만 할게요
1. 컵 추가 API 연결했습니다.

[AN][feat]: 물컵 설정 뷰 API 연결

---

README.md

[BE/AN][docs]: 리드미 업데이트

---

backend/src/main/java/backend/mulkkam/common/exception/GlobalExceptionHandler.java

[BE][refactor] GlobalExceptionHandler에서 메서드명 수정

---

backend/src/main/java/backend/mulkkam/cup/domain/vo/CupRank.java
backend/src/main/java/backend/mulkkam/cup/dto/request/CupRegisterRequest.java
backend/src/main/java/backend/mulkkam/cup/service/CupService.java
backend/src/test/java/backend/mulkkam/cup/domain/vo/CupAmountTest.java
backend/src/test/java/backend/mulkkam/cup/domain/vo/CupNicknameTest.java
backend/src/test/java/backend/mulkkam/cup/domain/vo/CupRankTest.java

- close #82 
- DTO에서 도메인을 생성하도록 합니다.
- 불필요한 개행을 삭제합니다.
- `ValueSource` 테스트시, int 값은 ints로 받도록 변경합니다.
- DTO에서 도메인을 생성하도록 합니다.
- 불필요한 개행을 삭제합니다.
- `ValueSource` 테스트시, int 값은 ints로 받도록 변경합니다.

[BE][refactor]: 컵 관련 리팩터링 진행

---

android/app/build.gradle.kts
android/app/src/main/java/com/mulkkam/ui/custom/GradientDonutChartView.kt
android/app/src/main/java/com/mulkkam/ui/history/HistoryFragment.kt
android/app/src/main/res/layout/history_water_intake_chart.xml
android/gradle/libs.versions.toml

- close #130 
- 기존 차트 라이브러리를 커스텀 뷰로 변경
https://github.com/user-attachments/assets/3331e4a2-f371-4873-9f68-8e7274636254

[AN][refactor]: 차트 라이브러리를 커스텀 뷰로 변경

---

backend/src/main/java/backend/mulkkam/intake/controller/IntakeAmountController.java
backend/src/main/java/backend/mulkkam/intake/dto/IntakeRecommendedAmountResponse.java
backend/src/main/java/backend/mulkkam/intake/dto/IntakeTargetAmountModifyRequest.java
backend/src/main/java/backend/mulkkam/intake/dto/IntakeTargetAmountResponse.java
backend/src/main/java/backend/mulkkam/intake/service/IntakeAmountService.java
backend/src/test/java/backend/mulkkam/intake/service/IntakeAmountServiceIntegrationTest.java
backend/src/test/java/backend/mulkkam/intake/service/IntakeAmountServiceUnitTest.java

- close #120 
- 목표 음용량 조회 기능
1. 목표 음용량 조회 기능 추가
2. 기존의 `IntakeAmount` 로 혼용되는 단어들을 모두 IntakeTargetAmount / IntakeRecommendedAmount 와 같이 명시

[BE][feat]: 사용자 목표 음용량 조회

---

android/app/src/main/java/com/mulkkam/data/remote/model/response/IntakeTargetAmountResponse.kt
android/app/src/main/java/com/mulkkam/data/remote/service/IntakeService.kt
android/app/src/main/java/com/mulkkam/data/repository/IntakeRepository.kt
android/app/src/main/java/com/mulkkam/ui/history/HistoryViewModel.kt
android/app/src/main/java/com/mulkkam/ui/home/HomeFragment.kt
android/app/src/main/java/com/mulkkam/ui/home/HomeViewModel.kt
android/app/src/main/res/layout/fragment_home.xml
android/app/src/main/res/values/strings.xml

- close #141 
- 홈화면에 접속할 시, 오늘 음용량 기록을 조회하고 화면에 반영합니다
1. 홈화면에 접속할 시, 오늘 음용량 기록 조회 및 progressBar 반영
2. 오늘 기록이 없을 시 목표 음용량 조회 및 progressBar 반영

[AN][feat]: 홈 화면 오늘 기록 조회 기능 추가

---

android/app/src/main/java/com/mulkkam/ui/home/HomeFragment.kt
android/app/src/main/java/com/mulkkam/ui/home/HomeViewModel.kt
android/app/src/main/res/layout/fragment_home.xml

- close #142 
- 홈 화면 컵 용량 버튼 추가
1. 홈 화면 컵 용량 버튼 추가

[AN][feat]: 홈 화면 컵 용량 버튼 추가

---

android/app/src/main/java/com/mulkkam/data/remote/model/request/IntakeHistoryRequest.kt
android/app/src/main/java/com/mulkkam/data/remote/service/IntakeService.kt
android/app/src/main/java/com/mulkkam/data/repository/IntakeRepository.kt
android/app/src/main/java/com/mulkkam/ui/home/HomeFragment.kt
android/app/src/main/java/com/mulkkam/ui/home/HomeViewModel.kt
android/app/src/main/res/layout/fragment_home.xml

- close #140
- 홈 화면에 마신 음용량을 기록
1. 음용량을 기록하는 API 연결
2. 컵 용량에 따른 버튼의 색상 변경
3.

[AN][feat]: 홈 화면 음용량 기록 API

---

.github/workflows/pr-title-sync.yml

- close #174 
- pr 제목을 issue 제목과 동기화하도록 workflow 설정
1. workflow 생성
2. 
3. 
merge이후에 기능을 테스트해볼 수 있어서 merge 가능 시 바로 테스트 해보겠습니다~

[BE/AN][feat]: pr 제목을 issue 제목과 동기화하도록 workflow 설정

---

backend/build.gradle
backend/src/main/java/backend/mulkkam/common/config/SwaggerConfig.java

- close #172 
- swagger 연동
1. 
2. 
3.

[BE][feat]: swagger 연동

---

.github/workflows/pr-title-init.yml

- close #192 
- pr 제목 초기화 workflow의 이벤트 조건 수정
1. pr 제목 초기화 workflow 이벤트 조건에서 `synchronize` 제거
merge가 되어야 테스트가 되는 issue 이므로 어푸 가능 시 바로 merge 진행하겠습니다~

[BE/AN][feat]: pr-title-init.yml 이벤트 발생 조건 수정

---

android/app/src/main/java/com/mulkkam/MulKkamApp.kt
android/app/src/main/java/com/mulkkam/data/preference/TokenPreference.kt
android/app/src/main/java/com/mulkkam/data/repository/TokenRepository.kt
android/app/src/main/java/com/mulkkam/di/PreferenceInjection.kt
android/app/src/main/java/com/mulkkam/di/RepositoryInjection.kt

- close #135
- TokenPreference 구현
1. TokenPreference 구현
2. TokenRepository 추가

[AN][feat]: TokenRepository 구현

---

android/app/src/main/java/com/mulkkam/ui/main/MainActivity.kt
android/app/src/main/res/values/strings.xml

- close #116
- MainActivity에서 뒤로가기를 두 번 누를 시 앱이 종료되도록 기능 추가헀습니다 !
1. 
2. 
3. 
https://github.com/user-attachments/assets/58872f50-670b-4bb4-9c81-58063cf399aa

[AN][feat]: 메인 액티비티에서 두 번 뒤로가기 클릭시 종료 기능 추가

---

android/app/src/main/java/com/mulkkam/ui/custom/GradientDonutChartView.kt
android/app/src/main/java/com/mulkkam/ui/custom/LinearGradientProgressBarView.kt
android/app/src/main/java/com/mulkkam/ui/home/HomeFragment.kt
android/app/src/main/res/layout/fragment_home.xml
android/app/src/main/res/values/strings.xml

- close #164 
- 홈 화면의 프로그레스바를 디자인해 보았사옵니다
1. 
2. 
3.

[AN][feat]: 홈 프로그레스바 디자인 구현

---

backend/src/main/resources/application-dev.yml

[BE][feat]: 에러 로그 모니터링 추가

---

.github/workflows/backend-cd.yml

[BE][chore]: CD 스크립트 수정

---

android/app/src/main/java/com/mulkkam/data/remote/model/response/IntakeHistoryResponse.kt
android/app/src/main/java/com/mulkkam/data/remote/model/response/IntakeHistorySummaryResponse.kt
android/app/src/main/java/com/mulkkam/data/remote/service/IntakeService.kt
android/app/src/main/java/com/mulkkam/data/repository/IntakeRepositoryImpl.kt
android/app/src/main/java/com/mulkkam/domain/IntakeHistory.kt
android/app/src/main/java/com/mulkkam/domain/repository/IntakeRepository.kt

- close #283 
- 음용량 조회 API 응답을 수정했사옵니다
1. 
2. 
3.

[AN][refactor]: 음용량 조회 응답 수정

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/mulkkam/data/remote/model/request/MembersPhysicalAtrributesRequest.kt
android/app/src/main/java/com/mulkkam/data/remote/model/response/MembersResponse.kt
android/app/src/main/java/com/mulkkam/data/remote/service/MembersService.kt
android/app/src/main/java/com/mulkkam/data/repository/MembersRepositoryImpl.kt
android/app/src/main/java/com/mulkkam/domain/Gender.kt
android/app/src/main/java/com/mulkkam/domain/model/MemberInfo.kt
android/app/src/main/java/com/mulkkam/domain/repository/MembersRepository.kt
android/app/src/main/java/com/mulkkam/ui/onboarding/OnboardingInfo.kt
android/app/src/main/java/com/mulkkam/ui/onboarding/OnboardingViewModel.kt
android/app/src/main/java/com/mulkkam/ui/onboarding/bioinfo/BioInfoFragment.kt
android/app/src/main/java/com/mulkkam/ui/onboarding/bioinfo/BioInfoViewModel.kt
android/app/src/main/java/com/mulkkam/ui/onboarding/bioinfo/Gender.kt
android/app/src/main/java/com/mulkkam/ui/onboarding/bioinfo/dialog/OnboardingWeightFragment.kt
android/app/src/main/java/com/mulkkam/ui/setting/SettingFragment.kt
android/app/src/main/java/com/mulkkam/ui/settingbioinfo/SettingBioInfoActivity.kt
android/app/src/main/java/com/mulkkam/ui/settingbioinfo/SettingBioInfoViewModel.kt
android/app/src/main/java/com/mulkkam/ui/settingbioinfo/dialog/SettingWeightFragment.kt
android/app/src/main/res/layout/activity_setting_bio_info.xml
android/app/src/main/res/layout/fragment_weight.xml
android/app/src/main/res/values/strings.xml

- close #286 
- 설정 화면에서 신체 정보 저장 API 를 연동했습니다
1. 
2. 
3. 
https://github.com/user-attachments/assets/087fab88-ab3e-454a-b845-d7e81556f766

[AN][feat]: 설정 화면 - 신체 정보 설정 API 연동

---

android/app/src/main/java/com/mulkkam/data/remote/model/response/AuthResponse.kt
android/app/src/main/java/com/mulkkam/ui/login/LoginActivity.kt
android/app/src/main/java/com/mulkkam/ui/model/AppAuthState.kt
android/app/src/main/java/com/mulkkam/ui/model/AppEntryState.kt
android/app/src/main/java/com/mulkkam/ui/onboarding/OnboardingActivity.kt
android/app/src/main/java/com/mulkkam/ui/splash/SplashActivity.kt
android/app/src/main/java/com/mulkkam/ui/splash/SplashViewModel.kt

- close #322 
- 스플래시 화면에서 토큰 & 온보딩 확인 로직 구현
1. 
2. 
3.

[AN][feat]: 스플래시 토큰 확인 로직 구현

---

android/app/src/main/java/com/mulkkam/data/remote/model/response/MembersCheckOnboardingResponse.kt
android/app/src/main/java/com/mulkkam/data/remote/service/MembersService.kt
android/app/src/main/java/com/mulkkam/data/repository/MembersRepositoryImpl.kt
android/app/src/main/java/com/mulkkam/domain/repository/MembersRepository.kt
android/app/src/main/java/com/mulkkam/ui/login/LoginActivity.kt
android/app/src/main/java/com/mulkkam/ui/login/LoginViewModel.kt
android/app/src/main/java/com/mulkkam/ui/splash/SplashActivity.kt
android/app/src/main/java/com/mulkkam/ui/splash/SplashViewModel.kt

- close #326 
- 제곧내
1. 
2. 
3.

[AN][feat]: 스플래시/로그인 온보딩 여부 확인 API 연결

---

backend/src/main/java/backend/mulkkam/member/service/MemberService.java

- close #331 
-  OauthAccount 수정
1. 
2. 
3.

[BE][fix]: OauthAccount 변경 감지 안되는 버그 수정

---

backend/src/main/java/backend/mulkkam/member/controller/NicknameController.java
backend/src/main/java/backend/mulkkam/member/service/MemberService.java

- close #333 
- 토큰 없이 닉네임 중복하도록 수정
1. 
2. 
3.

[BE][fix]: 온보딩 때 닉네임 중복 로직 구현

---

backend/src/main/java/backend/mulkkam/intake/controller/IntakeAmountController.java

[{BE}][fix]: intake/amount/target/recommended`@GetMapping`에서 body가 아닌 param을 사용하도록 수정

---

backend/src/main/java/backend/mulkkam/common/config/WebConfiguration.java

[BE][fix]: Resolver 가 영속화되도록 수정

---

backend/src/main/java/backend/mulkkam/intake/service/IntakeHistoryService.java
backend/src/main/java/backend/mulkkam/member/dto/response/ProgressInfoResponse.java
backend/src/main/java/backend/mulkkam/member/service/MemberService.java
backend/src/test/java/backend/mulkkam/member/service/MemberServiceIntegrationTest.java

- close #344 
- 기록이 없는 경우 -> 스냅샷
- 스냅샷이 오늘 등록된 경우 (ex. 회원가입한 날) -> 멤버의 목표 음용량

[BE][fix]: 오늘 현황 조회하는 경우 0이 반환되지 않도록 수정

---

android/app/src/main/java/com/mulkkam/data/remote/adapter/ResponseCall.kt
android/app/src/main/java/com/mulkkam/data/remote/model/request/AddCupRequest.kt
android/app/src/main/java/com/mulkkam/data/remote/model/request/PatchCupRequest.kt
android/app/src/main/java/com/mulkkam/data/remote/service/CupsService.kt
android/app/src/main/java/com/mulkkam/data/repository/CupsRepositoryImpl.kt
android/app/src/main/java/com/mulkkam/domain/repository/CupsRepository.kt
android/app/src/main/java/com/mulkkam/ui/custom/FlowLayout.kt
android/app/src/main/java/com/mulkkam/ui/custom/MulKkamChipGroup.kt
android/app/src/main/java/com/mulkkam/ui/custom/MulKkamChipGroupAdapter.kt
android/app/src/main/java/com/mulkkam/ui/custom/MulKkamChipView.kt
android/app/src/main/java/com/mulkkam/ui/settingcups/SettingCupsViewModel.kt
android/app/src/main/java/com/mulkkam/ui/settingcups/dialog/SettingCupFragment.kt
android/app/src/main/java/com/mulkkam/ui/settingcups/dialog/SettingCupViewModel.kt
android/app/src/main/res/color/selector_mulkkam_chip_label.xml
android/app/src/main/res/drawable/selector_mulkkam_chip.xml
android/app/src/main/res/layout/fragment_setting_cup.xml
android/app/src/main/res/layout/layout_mulkkam_chip.xml
android/app/src/main/res/values/strings.xml

- close #317
- 컵 추가/수정/삭제
1. 콜어댑터 일부 수정함 Unit일 발생하는 오류가 있어서
https://github.com/user-attachments/assets/e42e38f3-a950-4c8f-95a1-e77a012debc7

[AN][feat]: 나의 컵 추가/설정/삭제 구현

---

android/app/src/main/java/com/mulkkam/ui/main/MainActivity.kt
android/app/src/main/res/values/strings.xml

- close #354 
- 홈화면에서 알림 권한 요청 로직을 추가했습니다 ~
1. 
2. 
3.

[AN][feat]: 홈화면 알림 권한 요청 기능 추가

---

android/app/src/main/java/com/mulkkam/data/remote/model/response/MembersProgressInfoResponse.kt
android/app/src/main/java/com/mulkkam/data/remote/service/MembersService.kt
android/app/src/main/java/com/mulkkam/data/repository/MembersRepositoryImpl.kt
android/app/src/main/java/com/mulkkam/domain/IntakeHistorySummary.kt
android/app/src/main/java/com/mulkkam/domain/model/MembersProgressInfo.kt
android/app/src/main/java/com/mulkkam/domain/model/TodayProgressInfo.kt
android/app/src/main/java/com/mulkkam/domain/repository/MembersRepository.kt
android/app/src/main/java/com/mulkkam/ui/home/HomeFragment.kt
android/app/src/main/java/com/mulkkam/ui/home/HomeViewModel.kt
android/app/src/main/java/com/mulkkam/ui/settingtargetamount/SettingTargetAmountActivity.kt
android/app/src/main/res/layout/activity_login.xml
android/app/src/main/res/layout/fragment_home.xml
android/app/src/main/res/values/strings.xml

- close #341 
- 홈화면 당일 기록 요청 API 연결했습니다
1. 
2. 
3.

[AN][feat]: 홈 화면 당일 기록 API 요청

---

android/app/src/main/java/com/mulkkam/data/remote/model/response/IntakeHistoryDetailsResponse.kt
android/app/src/main/java/com/mulkkam/data/remote/model/response/MemberNickname.kt
android/app/src/main/java/com/mulkkam/data/remote/model/response/PhysicalAttributes.kt
android/app/src/main/java/com/mulkkam/data/remote/model/response/TargetAmount.kt
android/app/src/main/java/com/mulkkam/data/remote/service/IntakeService.kt
android/app/src/main/java/com/mulkkam/data/repository/IntakeRepositoryImpl.kt
android/app/src/main/java/com/mulkkam/domain/repository/IntakeRepository.kt
android/app/src/main/java/com/mulkkam/ui/history/HistoryFragment.kt
android/app/src/main/java/com/mulkkam/ui/history/HistoryViewModel.kt

- close #340 
- 기록 화면 상세 내역 삭제 API 연결
1. 기록 화면 상세 내역 삭제 API 연결

[AN][feat]: 기록 화면 상세내역 삭제 API 연결

---

backend/src/main/java/backend/mulkkam/notification/service/NotificationService.java

[BE][fix]: 활동량 기반 suggestion 알림 로직 순서 변경

---

backend/src/main/java/backend/mulkkam/notification/controller/NotificationController.java
backend/src/main/java/backend/mulkkam/notification/service/ActivityService.java
backend/src/main/java/backend/mulkkam/notification/service/NotificationService.java

[BE][fix]: @Transactional 적용 안되는 거 수정 처리

---

backend/src/main/java/backend/mulkkam/common/config/WebConfiguration.java
backend/src/main/java/backend/mulkkam/common/exception/GlobalExceptionHandler.java
backend/src/main/java/backend/mulkkam/common/exception/errorCode/InterServerErrorCode.java
backend/src/main/java/backend/mulkkam/common/exception/errorCode/InternalServerErrorErrorCode.java
backend/src/main/java/backend/mulkkam/common/filter/JwtAuthenticationFilter.java

- close #373 
- Internal Server Error 전용 에러 코드 선언
- CommonException 이외에도 가장 상위의 `Exception` 잡히도록 수정
`Exception] code=INTER_SERVER_ERROR_CODE, status=500 INTERNAL_SERVER_ERROR, exception=IllegalArgumentException, message=존재하지 않는 회원입니다, uri=/members, method=POST` 이렇게 에러가 찍혀요

[BE][chore]: 로그 레벨 수정

---

backend/src/main/java/backend/mulkkam/averageTemperature/serivce/ScheduleService.java

[BE][tmp]: 날씨 스케줄링 알림 시간 변경

---

android/app/src/main/java/com/mulkkam/ui/home/HomeFragment.kt
android/app/src/main/java/com/mulkkam/ui/home/HomeViewModel.kt
android/app/src/main/java/com/mulkkam/ui/home/dialog/ManualDrinkFragment.kt
android/app/src/main/res/values/strings.xml

- close #387 
- 섭취 기록에 성공했을 때 ml 기록 Snackbar를 추가 ~
1. 
2. 
3.

[AN][feat]: 섭취 성공시 SnackBar 출력

---

android/app/src/main/java/com/mulkkam/ui/onboarding/terms/TermsFragment.kt
android/app/src/main/java/com/mulkkam/ui/onboarding/terms/TermsViewModel.kt
android/app/src/main/java/com/mulkkam/ui/onboarding/terms/adapter/TermsAdapter.kt
android/app/src/main/java/com/mulkkam/ui/onboarding/terms/adapter/TermsAgreementHandler.kt
android/app/src/main/java/com/mulkkam/ui/onboarding/terms/adapter/TermsAgreementViewHolder.kt
android/app/src/main/res/layout/fragment_terms.xml
android/app/src/main/res/layout/item_terms_agreement.xml

- close #391 
- 약관 동의 화면에서 클릭 영역 수정
1. 약관 동의 화면에서 클릭 영역 수정 // checkbox + textView를 LinearLayout으로 감싸서 clickListener 달아 줬습니다 ~
2. 선택 동의 항목이 항상 false로 가던 버그 수정
3.

[AN][refactor]: 온보딩 텍스트 클릭해도 약관 동의 체크되게 (피그마 반영)

---

android/app/src/main/java/com/mulkkam/ui/splash/SplashViewModel.kt

- close #393 
- 제곧내입니다
1. 
2. 
3.

[AN][refactor]: 스플래시 인증 실패시 로그인 화면으로 이동

---

android/app/src/main/java/com/mulkkam/data/logger/LoggerImpl.kt
android/app/src/main/java/com/mulkkam/di/LoggingInjection.kt
android/app/src/main/java/com/mulkkam/di/NetworkInjection.kt

- 로거 생성 시 주입받도록 의존성 수정
- 메서드 분리 및 네이밍 개선
- close #403
- 로거 구현체 개선
1. 함수 분리
2. 생성자에 의존성 주입받도록 설정

[AN][refactor]: 로깅 내부 로직 리팩터링

---

.github/workflows/pr-assign-init.yml
android/app/src/main/java/com/mulkkam/data/remote/model/request/MembersRequest.kt
android/app/src/main/java/com/mulkkam/data/remote/model/response/MembersResponse.kt
android/app/src/main/java/com/mulkkam/data/repository/IntakeRepositoryImpl.kt
android/app/src/main/java/com/mulkkam/data/repository/MembersRepositoryImpl.kt
android/app/src/main/java/com/mulkkam/domain/model/BioWeight.kt
android/app/src/main/java/com/mulkkam/domain/model/MemberInfo.kt
android/app/src/main/java/com/mulkkam/domain/model/OnboardingInfo.kt
android/app/src/main/java/com/mulkkam/domain/repository/IntakeRepository.kt
android/app/src/main/java/com/mulkkam/domain/repository/MembersRepository.kt
android/app/src/main/java/com/mulkkam/ui/onboarding/OnboardingViewModel.kt
android/app/src/main/java/com/mulkkam/ui/onboarding/bioinfo/BioInfoFragment.kt
android/app/src/main/java/com/mulkkam/ui/onboarding/bioinfo/BioInfoViewModel.kt
android/app/src/main/java/com/mulkkam/ui/onboarding/bioinfo/dialog/OnboardingWeightFragment.kt
android/app/src/main/java/com/mulkkam/ui/onboarding/targetamount/TargetAmountViewModel.kt
android/app/src/main/java/com/mulkkam/ui/settingbioinfo/SettingBioInfoActivity.kt
android/app/src/main/java/com/mulkkam/ui/settingbioinfo/SettingBioInfoViewModel.kt
android/app/src/main/java/com/mulkkam/ui/settingbioinfo/dialog/SettingWeightFragment.kt

- close #411
- 로직이 특별히 없어서 바로 value class로 반환하게 만들었습니다.
1. BioWeight 클래스 구현
2. 몸무게 범위 확장

[AN][refactor]: 몸무게 도메인 모델로 설정

---

backend/src/main/java/backend/mulkkam/common/filter/JwtAuthenticationFilter.java
backend/src/main/resources/application.yml

- 액츄에이터 노출 포트 변경
- filter exclude url 목록에 불필요한 값 삭제
액츄에이터 포트를 8081로 변경했습니다
> 모니터링 시스템에서 액츄에이터에 health 정보를 조회하는 기능이 있었던 것 같아서, 해당 부분 반영한 후에 머지하면 될 것 같아요

[BE][chore] 액츄에이터 포트 변경

---

backend/build.gradle
backend/src/main/java/backend/mulkkam/common/config/MetricConfiguration.java
backend/src/main/resources/application.yml

- close #415 
- 8081 -> 80 으로 적용되도록 포트 관련 설정 삭제
- spring server 가 알아서 cloudwatch 에 메트릭 정보를 전송하도록 수정

[BE][chore]: actuator 수집 메트릭 관련 경로 설정

---

.github/workflows/backend-cd.yml
backend/src/main/java/backend/mulkkam/common/exception/GlobalExceptionHandler.java
backend/src/main/java/backend/mulkkam/common/filter/ApiPerformanceInterceptor.java
backend/src/main/resources/application-dev.yml
backend/src/main/resources/application-local.yml
backend/src/main/resources/logback-spring.xml

[BE][feat]: 로그백 설정

---

backend/src/main/resources/logback-spring.xml

[BE][feat]: 로깅 지표 필터를 위한 JSON 추가

---

android/app/src/main/java/com/mulkkam/ui/history/HistoryViewModel.kt
android/app/src/test/java/com/mulkkam/ui/fixture/HistoryFixture.kt
android/app/src/test/java/com/mulkkam/ui/history/HistoryViewModelTest.kt

- close #420 
- HistoryViewModel의 테스트 코드를 야무지게 짜 보았습니다
1. 피드백 적극 환영
2. 
3.

[AN][test]: HistoryViewModel 테스트 코드 작성

---

android/app/src/main/java/com/mulkkam/domain/model/bio/BioWeight.kt
android/app/src/main/java/com/mulkkam/ui/onboarding/bioinfo/BioInfoViewModel.kt
android/app/src/main/java/com/mulkkam/ui/settingbioinfo/SettingBioInfoViewModel.kt

- close #454
- 사실 특별한건 없어서~~
1. require를 사용했기 때문에 생성할 때 runCatching을 사용하도록 두었습니다

[AN][refactor] 몸무게 최대치 수정

---

android/app/build.gradle.kts
android/app/src/main/java/com/mulkkam/ui/history/HistoryFragment.kt
android/app/src/main/java/com/mulkkam/ui/history/HistoryViewModel.kt
android/app/src/main/res/layout/fragment_history.xml
android/app/src/main/res/layout/layout_history_shimmer.xml
android/app/src/test/java/com/mulkkam/ui/history/HistoryViewModelTest.kt
android/gradle/libs.versions.toml

- close #471 
- 이것저것 작업...
1. 기록 화면 로딩 상태 추가
2. 스켈레톤 UI 추가
https://github.com/user-attachments/assets/ca98854b-c8ce-4a75-9ca6-8c5433a81473

[AN][feat]: 기록 화면 Loading State 구현

---

.github/workflows/backend-cd.yml
backend/src/main/java/backend/mulkkam/common/filter/HttpLoggingFilter.java

- close #464
- response body log 시 마지막 } 접합
1. 
2. 
3.

[BE][feat]: 로깅 구조 개선

---

backend/src/main/java/backend/mulkkam/member/controller/MemberController.java
backend/src/main/java/backend/mulkkam/member/domain/Member.java
backend/src/main/java/backend/mulkkam/member/dto/request/ModifyIsMarketingNotificationAgreedRequest.java
backend/src/main/java/backend/mulkkam/member/service/MemberService.java
backend/src/test/java/backend/mulkkam/member/controller/MemberControllerTest.java

- close #499 
- 마케팅 수신 알림 수정 로직을 구현합니다.
1. 
2. 
3.

[BE][feat]: 마케팅 수신 알림 수정 로직 구현

---

android/app/src/main/java/com/mulkkam/data/logger/LoggerImpl.kt
android/app/src/main/java/com/mulkkam/data/logger/SensitiveInfoSanitizerImpl.kt
android/app/src/main/java/com/mulkkam/domain/model/logger/LogEntry.kt

- close #507
- 아니 타임스탬프 만들어놓고 안쓰고 있었네요?
1. 타임스탬프 출력 추가
2. 저번에 IP 까먹고 둘뻔한거 생각나서 IP도 가림
```kotlin
2025-08-14 14:56:10.408  1677-1806  [MULKKAM_LOGGER]        com.mulkkam                          D  level=DEBUG, event=NETWORK
timestamp=2025-08-14T14:56:10.407641+09:00
message=
🛡️️ Response: 401  (41ms)
URL: http://***/members/check/onboarding
Body: {"timestamp":"2025-08-14T05:56:21.188+00:00","status":401,"error":"Unauthorized","path":"/members/check/onboarding"} | userId=null
```

[AN][refactor]: 로그 표준시 변경

---

android/app/src/main/java/com/mulkkam/domain/model/logger/LogEvent.kt
android/app/src/main/java/com/mulkkam/ui/setting/SettingFragment.kt
android/app/src/main/java/com/mulkkam/ui/setting/adapter/SettingAdapter.kt
android/app/src/main/java/com/mulkkam/ui/setting/adapter/SettingDiffCallback.kt
android/app/src/main/java/com/mulkkam/ui/setting/adapter/SettingItem.kt
android/app/src/main/java/com/mulkkam/ui/setting/adapter/SettingViewType.kt
android/app/src/main/java/com/mulkkam/ui/setting/adapter/SwitchViewHolder.kt
android/app/src/main/java/com/mulkkam/ui/setting/model/SettingType.kt
android/app/src/main/res/values/strings.xml

[AN][feat]: 개빠른 설정 화면 구현

---

backend/src/main/java/backend/mulkkam/member/service/MemberService.java

[BE][feat]: 멤버 알림 세팅 조회 로직

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/mulkkam/ui/onboarding/OnboardingActivity.kt
android/app/src/main/java/com/mulkkam/ui/onboarding/OnboardingStep.kt
android/app/src/main/java/com/mulkkam/ui/onboarding/terms/TermsAgreementFragment.kt
android/app/src/main/java/com/mulkkam/ui/onboarding/terms/TermsAgreementViewModel.kt
android/app/src/main/java/com/mulkkam/ui/onboarding/terms/adapter/TermsAgreementAdapter.kt
android/app/src/main/java/com/mulkkam/ui/setting/SettingFragment.kt
android/app/src/main/java/com/mulkkam/ui/settingfeedback/SettingFeedbackActivity.kt
android/app/src/main/java/com/mulkkam/ui/settingterms/SettingTermsActivity.kt
android/app/src/main/java/com/mulkkam/ui/settingterms/SettingTermsViewModel.kt
android/app/src/main/java/com/mulkkam/ui/settingterms/TermsUiModel.kt
android/app/src/main/java/com/mulkkam/ui/settingterms/adapter/TermsAdapter.kt
android/app/src/main/java/com/mulkkam/ui/settingterms/adapter/TermsViewHolder.kt
android/app/src/main/java/com/mulkkam/ui/util/extensions/ContextExtensions.kt
android/app/src/main/res/layout/activity_setting_feedback.xml
android/app/src/main/res/layout/activity_setting_terms.xml
android/app/src/main/res/layout/fragment_terms.xml
android/app/src/main/res/values/strings.xml
android/app/src/main/res/values/uris.xml

- close #526 
- 고객센터 뷰를 구현
1. 피드백 화면 구현
2. 약관 동의 이동 구현
3. 
https://github.com/user-attachments/assets/48b01f35-bc52-4c58-aecf-43fd882a98fa

[AN][feat]: 설정 뷰 고객센터 구현

---

backend/src/main/java/backend/mulkkam/common/exception/GlobalExceptionHandler.java
backend/src/main/java/backend/mulkkam/common/filter/HttpLoggingFilter.java
backend/src/main/java/backend/mulkkam/common/filter/JwtAuthenticationFilter.java
backend/src/main/java/backend/mulkkam/common/interceptor/ApiPerformanceInterceptor.java
backend/src/main/java/backend/mulkkam/common/resolver/MemberResolver.java
backend/src/main/java/backend/mulkkam/common/resolver/OauthAccountResolver.java
backend/src/test/java/backend/mulkkam/common/resolver/MemberResolverTest.java
backend/src/test/java/backend/mulkkam/common/resolver/OauthAccountResolverTest.java

I'm so sorry..
- close #546 
- 
1. 
2. 
3.

[BE][fix]: Member 리졸버에서 OauthAccount id 전달하는 문제

---

android/app/src/main/res/layout/activity_setting_nickname.xml
android/app/src/main/res/layout/fragment_nickname.xml

- close #539 
- 제목이 곧 내용
2줄 피알 멋지죠
1. 
2. 
3. 
https://github.com/user-attachments/assets/401b8517-3f75-4384-a1dd-049439fde21d

[AN][refactor]: 닉네임 입력 글자수 제한

---

backend/src/main/java/backend/mulkkam/cup/controller/CupController.java
backend/src/main/java/backend/mulkkam/intake/controller/IntakeAmountController.java
backend/src/main/java/backend/mulkkam/intake/controller/IntakeHistoryController.java
backend/src/main/java/backend/mulkkam/intake/dto/CreateIntakeHistoryResponse.java
backend/src/main/java/backend/mulkkam/intake/dto/RecommendedIntakeAmountResponse.java
backend/src/main/java/backend/mulkkam/intake/dto/request/IntakeDetailCreateRequest.java
backend/src/main/java/backend/mulkkam/intake/dto/request/IntakeTargetAmountModifyRequest.java
backend/src/main/java/backend/mulkkam/intake/dto/request/ModifyIntakeTargetAmountByRecommendRequest.java
backend/src/main/java/backend/mulkkam/intake/dto/response/IntakeDetailResponse.java
backend/src/main/java/backend/mulkkam/intake/dto/response/IntakeHistorySummaryResponse.java
backend/src/main/java/backend/mulkkam/intake/dto/response/IntakeRecommendedAmountResponse.java
backend/src/main/java/backend/mulkkam/intake/dto/response/IntakeTargetAmountResponse.java
backend/src/main/java/backend/mulkkam/intake/repository/TargetAmountSnapshotRepository.java
backend/src/main/java/backend/mulkkam/intake/service/IntakeHistoryService.java
backend/src/main/java/backend/mulkkam/member/controller/MemberController.java
backend/src/main/java/backend/mulkkam/member/dto/CreateMemberRequest.java
backend/src/main/java/backend/mulkkam/member/dto/response/MemberResponse.java
backend/src/main/java/backend/mulkkam/member/dto/response/ProgressInfoResponse.java
backend/src/test/java/backend/mulkkam/cup/service/CupServiceIntegrationTest.java
backend/src/test/java/backend/mulkkam/cup/service/CupServiceUnitTest.java
backend/src/test/java/backend/mulkkam/intake/controller/IntakeHistoryControllerTest.java
backend/src/test/java/backend/mulkkam/intake/service/IntakeHistoryServiceIntegrationTest.java
backend/src/test/java/backend/mulkkam/intake/service/IntakeHistoryServiceUnitTest.java
backend/src/test/java/backend/mulkkam/intake/service/IntakeTargetAmountServiceIntegrationTest.java
backend/src/test/java/backend/mulkkam/intake/service/IntakeTargetAmountServiceUnitTest.java
backend/src/test/java/backend/mulkkam/notification/service/NotificationServiceIntegrationTest.java
backend/src/test/java/backend/mulkkam/notification/service/NotificationServiceUnitTest.java

- 기존에는 조회날과 스냅샷변경 날짜가 같다면 바뀐 스냅샷을 조회하지 못하던 버그를 수정합니다.
- close #548 
- 
1. 
2. 
3.

[BE][fix]: 목표 음용량 스냅샷 조회 버그 수정

---

backend/src/main/java/backend/mulkkam/intake/domain/vo/RecommendAmount.java
backend/src/main/java/backend/mulkkam/member/domain/vo/PhysicalAttributes.java
backend/src/main/java/backend/mulkkam/member/dto/response/MemberResponse.java
backend/src/test/java/backend/mulkkam/member/controller/MemberControllerTest.java
backend/src/test/java/backend/mulkkam/member/service/MemberServiceIntegrationTest.java
backend/src/test/java/backend/mulkkam/member/service/MemberServiceUnitTest.java

- close #564 
- 몸무게 및 성별 null 저장, 조회 로직 추가합니다.
1. 
2. 
3.

[BE][feat]: 몸무게 및 성별 null일 시, 기본값이 아닌 null  반환하도록 변경

---

backend/src/main/resources/application-dev.yml

이전 작업에서 dev profile 푸시를 안한 것 같네요 ,,

[BE][fix] dev profile 누락

---

backend/src/main/java/backend/mulkkam/common/resolver/MemberResolver.java
backend/src/test/java/backend/mulkkam/common/resolver/MemberResolverTest.java

[BE][fix]: 최초 회원가입/로그인 시 member id 값 미결정되어 404 에러 뜨는 문제 해결

---

.github/workflows/backend-prod-cd.yml

[BE][fix]: release 브랜치 상에서 CD 트리거가 안되는 오류 해결

---

.github/workflows/backend-prod-rollback.yml

- close #619 
- 프로덕션 수동 롤백 워크플로우 추가
1. rollback yml 파일 추가

[BE][chore]: 프로덕션 수동 롤백 스크립트 추가

---

.github/workflows/backend-prod-rollback.yml
backend/src/main/java/backend/mulkkam/MulKkamApplication.java

[BE][fix]: 수동 롤백 스크립트 경로 오류 수정

---

backend/src/main/resources/application-prod.yml

- close #597 
- `AWS CloudWatch` 모니터링에 필요한 메트릭 수집 설정
1. `application-prod.yml` 내용 추가
- 프로덕션 서버 `AWS CloudWatch agent` 설치 완료
- (임시) 수집 정보
- EC2 시스템 메트릭 (by `agent config file`)
- `cpu_usage_idle` - cpu 유휴 시간 비율
- `cpu_usage_nice` - 낮은 우선순위로 실행된 프로세스가 사용한 CPU 시간
- 어플리케이션 시스템 메트릭
- `jvm.memory.used`
- `jvm.memory.max`
- `jvm.gc.pause`
- `jvm.threads`
- `hikaricp`
- `http.server`
- `process.cpu`

[BE][chore]: 프로덕션 ec2 CloudWatch 모니터링 적용을 위한 설정 추가

---

.github/workflows/backend-dev-cd.yml
backend/src/main/java/backend/mulkkam/common/config/datasource/DataSourceConfig.java
backend/src/main/java/backend/mulkkam/common/config/datasource/DatabaseRole.java
backend/src/main/java/backend/mulkkam/common/config/datasource/ReadWriteRoutingDataSource.java
backend/src/main/resources/application-dev.yml

[BE][feat]: 데이터베이스 권한 설정

---

.github/workflows/android-ci.yml

[AN][fix]: CI에 잘못 들어간 키값 수정

---

backend/src/main/java/backend/mulkkam/intake/dto/request/CreateIntakeHistoryDetailByCupRequest.java
backend/src/test/java/backend/mulkkam/intake/controller/IntakeHistoryControllerTest.java
backend/src/test/java/backend/mulkkam/intake/service/IntakeHistoryServiceIntegrationTest.java

[BE][fix]: 컵 섭취 API 요청 형식 변경

---

backend/src/main/java/backend/mulkkam/intake/domain/vo/RecommendAmount.java
backend/src/main/java/backend/mulkkam/intake/dto/response/IntakeHistorySummaryResponse.java
backend/src/main/java/backend/mulkkam/intake/service/IntakeAmountService.java
backend/src/main/java/backend/mulkkam/intake/service/IntakeHistoryService.java
backend/src/main/java/backend/mulkkam/member/domain/vo/TargetAmount.java
backend/src/main/java/backend/mulkkam/notification/dto/CreateActivityNotification.java
backend/src/main/java/backend/mulkkam/notification/service/SuggestionNotificationService.java

[BE][hotfix]: 운동 알림 추가시 더할 값을 보내도록 수정

---

android/app/src/main/java/com/mulkkam/ui/setting/SettingFragment.kt
android/app/src/main/java/com/mulkkam/ui/setting/SettingViewModel.kt
android/app/src/main/java/com/mulkkam/ui/settingcups/SettingCupsActivity.kt
android/app/src/main/java/com/mulkkam/ui/settingcups/SettingCupsViewModel.kt
android/app/src/main/java/com/mulkkam/ui/settingcups/adapter/SettingCupsAdapter.kt
android/app/src/main/java/com/mulkkam/ui/settingcups/dialog/SettingCupFragment.kt
android/app/src/main/java/com/mulkkam/ui/util/extensions/BundleExtensions.kt
android/app/src/main/java/com/mulkkam/ui/util/extensions/IntentExtensions.kt

- close #703
- 낙관적 UI가 rank를 바꾸지는 않고 있더라구요? 어려운것,,,
- 서버에서 딜레이 넣어달라고 했는데 그 딜레이때문에 또 문제가 생기더라구요...? 제 능력 밖의 일인가보오...
1. 서버 전송하는 딜레이 제거
2. 라이브데이터를 그대로 갱신하면 무반응인 오류 제거
https://github.com/user-attachments/assets/02a67aeb-6108-43d6-a43a-e8dd4eaa63d6

[AN][fix]: 대표 컵 순서 라벨 오류

---

android/app/src/main/java/com/mulkkam/ui/custom/toast/CustomToast.kt
android/app/src/main/java/com/mulkkam/ui/notification/NotificationActivity.kt
android/app/src/main/java/com/mulkkam/ui/notification/adapter/NotificationViewHolder.kt
android/app/src/main/java/com/mulkkam/ui/onboarding/nickname/NicknameFragment.kt
android/app/src/main/java/com/mulkkam/ui/settingaccountinfo/SettingAccountInfoActivity.kt
android/app/src/main/java/com/mulkkam/ui/settingaccountinfo/dialog/AccountDeleteDialogFragment.kt
android/app/src/main/java/com/mulkkam/ui/settingnickname/SettingNicknameActivity.kt

- close #701
- 기존에 edit text에서 Trim을 하면 커서가 이상하게 이동되는 문제...
- 이를 수정하기 위해 trim을 다 죽여 버렸습니다
1. 
2. 
3. 
https://github.com/user-attachments/assets/86655212-c90b-4c7d-90e9-44ab245290ef

[AN][fix]: 입력 시 띄어쓰기 커서 오류 수정

---

android/app/src/main/java/com/mulkkam/data/remote/interceptor/AuthorizationInterceptor.kt
android/app/src/main/java/com/mulkkam/data/remote/model/response/auth/AuthReissueResponse.kt
android/app/src/main/java/com/mulkkam/data/remote/model/response/auth/AuthResponse.kt
android/app/src/main/java/com/mulkkam/data/repository/AuthRepositoryImpl.kt
android/app/src/main/java/com/mulkkam/domain/model/auth/AuthInfo.kt
android/app/src/main/java/com/mulkkam/domain/repository/AuthRepository.kt
android/app/src/main/java/com/mulkkam/ui/login/LoginViewModel.kt

- close #740
- 로그인 시 온보딩 여부 필드 활용 로직 수정
1. 
2. 
3.

[AN][refactor]: 로그인 시 온보딩 여부 확인 로직 변경

---

backend/src/main/java/backend/mulkkam/MulKkamApplication.java

[BE][TMP] flyway 재빌드용

---

backend/src/main/resources/application-dev.yml

tmp: baseline-on-migrate 를 false로 변경

---

android/app/src/main/java/com/mulkkam/ui/onboarding/cups/dialog/CupBottomSheetViewModel.kt
android/app/src/main/java/com/mulkkam/ui/settingcups/dialog/SettingCupViewModel.kt

- close #806 
- 컵 수정 dialog에서 이름과 용량 모두 수정해야 수정 가능하던 버그를 고쳐 봤습니다...
1. 
2. 
3. 
https://github.com/user-attachments/assets/6d6d34e3-c73c-4246-85bb-7d05c489b02a

[AN][fix]: 컵 수정 BottomSheet 버그 수정

---

android/app/src/main/res/values/strings.xml

- close #836
- 커피 스낵바의 문구 변경
1. 커피 스낵바 문구 변경

[AN][refactor]: 커피 스낵바 문구 변경

---

android/app/src/main/res/values/strings.xml

- close #850 
- 네... 지워 버렸습니다 ~
1. 
2. 
3.

[AN][refactor]: 커피 백과사전 챗지피티 없애기

---

.github/workflows/android-ci.yml

[AN][feat]: FCM 서버 분리
